import { Outlet } from "react-router-dom"
import { useEffect } from "react"
import { FaPrint } from "react-icons/fa"

/**
 * Print-friendly layout for invoices, booking confirmations, and other printable content
 * Automatically triggers print dialog when loaded
 */
const PrintLayout = () => {
    // Add print-specific styles when component mounts
    useEffect(() => {
        // Add print-specific class to body
        document.body.classList.add("print-mode")

        // Remove the class when component unmounts
        return () => {
            document.body.classList.remove("print-mode")
        }
    }, [])

    // Handle print action
    const handlePrint = () => {
        window.print()
    }

    return (
        <div className="min-h-screen bg-white">
            {/* Print header - only visible on screen, not in print */}
            <header className="bg-primary-600 text-white py-4 print:hidden">
                <div className="container mx-auto px-4">
                    <div className="flex justify-between items-center">
                        <h1 className="text-xl font-bold">StayFinder</h1>
                        <button
                            onClick={handlePrint}
                            className="flex items-center bg-white text-primary-600 px-4 py-2 rounded-lg hover:bg-primary-50 transition-colors"
                        >
                            <FaPrint className="mr-2" />
                            <span>Print</span>
                        </button>
                    </div>
                </div>
            </header>

            {/* Main content - optimized for printing */}
            <main className="container mx-auto px-4 py-8 print:py-0 print:px-0">
                <div className="bg-white rounded-lg shadow-lg print:shadow-none p-8 print:p-0">
                    <Outlet />
                </div>
            </main>

            {/* Print footer - only visible on screen, not in print */}
            <footer className="mt-8 text-center text-secondary-500 print:hidden">
                <p>This document was generated by StayFinder.</p>
                <p className="text-sm mt-2">
                    &copy; {new Date().getFullYear()} StayFinder. All rights
                    reserved.
                </p>
            </footer>

            {/* Print-only footer that appears at the bottom of the printed page */}
            <footer className="hidden print:block text-center text-xs text-secondary-500 mt-8 pt-4 border-t border-secondary-200">
                <p>
                    Generated by StayFinder on {new Date().toLocaleDateString()}
                </p>
            </footer>
        </div>
    )
}

export default PrintLayout
